x-stop-grace-period: &stop-grace-period-policy
    # NOTE: Voting round 90s + reveal deadline 45s + signatures grace 10s
    stop_grace_period: 145s 

x-restart: &restart-policy
    restart: unless-stopped

volumes:
  indexer_data:

services:
  c-chain-indexer-db:
    <<: *restart-policy
    image: "mysql:9.5.0@sha256:57c892ddeb17e6c7dddf219914db017b2cf3e2797806a75424444b83622cc8ef"
    profiles: [fsp, ftso, fdc, tee]
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - indexer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--host", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  c-chain-indexer:
    <<: *restart-policy
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:v1.1.3@sha256:262778a5ca4bb8b6a6c297ea118c3d87fdf640757b316c5cebe8f41be6466dd9
    profiles: [fsp, ftso, fdc, tee]
    environment:
      # db
      DB_HOST: "c-chain-indexer-db"
      DB_PORT: 3306
      DB_DATABASE: "flare_ftso_indexer"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      # node
      NODE_API_KEY: ${NODE_API_KEY}
      NODE_URL: ${NODE_RPC_URL}
    volumes:
      - ./mounts/c-chain-indexer/config.toml:/app/config.toml
    depends_on:
      c-chain-indexer-db:
        condition: service_healthy

  system-client:
    <<: [*restart-policy, *stop-grace-period-policy]
    image: ghcr.io/flare-foundation/flare-system-client:v1.1.1@sha256:239d91f7a3c9170cfa0c72059aaa52a947f2bdc970f8c28e2120d519d8bce7ce
    profiles: [fsp, system-client]
    environment:
      # db
      DB_HOST: "c-chain-indexer-db"
      DB_PORT: 3306
      DB_DATABASE: "flare_ftso_indexer"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      # node
      ETH_RPC_URL: ${NODE_RPC_URL}
      API_KEY: ${NODE_API_KEY}
      # private keys
      SYSTEM_CLIENT_SENDER_PRIVATE_KEY: ${SIGNING_PK}
      SIGNING_POLICY_PRIVATE_KEY: ${SIGNING_PK}
      PROTOCOL_MANAGER_SUBMIT_PRIVATE_KEY: ${SUBMIT_PK}
      PROTOCOL_MANAGER_SUBMIT_SIGNATURES_PRIVATE_KEY: ${SIGNATURES_PK}
      # underlying client api keys
      PROTOCOL_X_API_KEY_100: ${PROTOCOL_X_API_KEY_100}
      PROTOCOL_X_API_KEY_200: ${PROTOCOL_X_API_KEY_200}
    volumes:
      - ./mounts/system-client/config.toml:/app/config.toml
    depends_on:
      - c-chain-indexer

  ftso-client:
    <<: [*restart-policy, *stop-grace-period-policy]
    image: ghcr.io/flare-foundation/ftso-scaling:v1.1.1@sha256:e61dbbcf4a84853ab37805a09745c130b9012e0908a47a810e38f280dc151759
    profiles: [fsp, ftso]
    environment:
      DB_HOST: "c-chain-indexer-db"
      DB_PORT: 3306
      DB_NAME: "flare_ftso_indexer"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
    env_file:
      - ./mounts/ftso-client/.env
    depends_on:
      - c-chain-indexer

  fdc-client:
    <<: [*restart-policy, *stop-grace-period-policy]
    image: ghcr.io/flare-foundation/fdc-client:v1.3.0@sha256:30f1a4d1dd651b99a21048f5bb667612f2ef71d07b10dad6f59c019e408c8566
    profiles: [fsp, fdc]
    environment:
      DB_HOST: "c-chain-indexer-db"
      DB_PORT: 3306
      DB_DATABASE: "flare_ftso_indexer"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
    volumes:
      - ./mounts/fdc-client/config.toml:/app/configs/userConfig.toml
    depends_on:
      - c-chain-indexer

  tee-relay-client:
    <<: *restart-policy
    image: ghcr.io/flare-foundation/tee-relay-client:v0.0.2@sha256:74e963259c96d77d84df1fdd31f3b2c1d120fb010cff66d02e96b748848a6810
    profiles: [tee]
    environment:
      # signing policy key for providers, designated cosigning key for cosigners
      PRIVATE_KEY: ${SIGNING_PK}
    volumes:
      - ./mounts/tee-relay-client/config.toml:/app/config.toml
    depends_on:
      - c-chain-indexer

  fast-updates:
    <<: *restart-policy
    image: ghcr.io/flare-foundation/fast-updates/go-client:v1.0.2@sha256:c07cda6f26e0294647225ee00e6414d843ec4765f5d32393c2e0d2acdbdaa9f7
    profiles: [fast-updates]
    environment:
      SIGNING_PRIVATE_KEY: ${SIGNING_PK}
      ACCOUNTS: ${FAST_UPDATES_ACCOUNTS}
      SORTITION_PRIVATE_KEY: ${FAST_UPDATES_SORTITION_PRIVATE_KEY}
      NODE_URL: ${NODE_RPC_URL}
      API_KEY: ${NODE_API_KEY}
    volumes:
      - ./mounts/fast-updates/config.toml:/app/config.toml
    depends_on:
      - c-chain-indexer
