[indexer]
num_parallel_req = 100 # the number of threads doing requests to the chain in parallel
batch_size = 1000 # the number of blocks that will be pushed to a database in a batch (should be divisible by num_parallel_req)
log_range = 10 # the size of the interval of blocks used to request logs in each request; suggested value is log_range = batch_size / num_parallel_req; note that a blockchain node might have an upper bound on this
new_block_check_millis = 1000 # interval for checking for new blocks

# standard config
[[indexer.collect_transactions]]
contract_address = "$SUBMISSION" # Submission
func_sig = "6c532fae"
status = true

[[indexer.collect_transactions]]
contract_address = "$SUBMISSION" # Submission
func_sig = "9d00c9fd"
status = true

[[indexer.collect_transactions]]
contract_address = "$SUBMISSION" # Submission
func_sig = "57eed580"
status = true

[[indexer.collect_transactions]]
contract_address = "$RELAY" # Relay
func_sig = "b59589d1"
status = true
collect_events = true

[[indexer.collect_logs]]
contract_address = "$FLARE_SYSTEMS_MANAGER" # FlareSystemsManager
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$VOTER_REGISTRY" # VoterRegistry
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x2580101692366e2f331e891180d9ffdF861Fce83" # Flare: Legacy VoterRegistry
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x31B9EC65C731c7D973a33Ef3FC83B653f540dC8D" # Songbird: Legacy VoterRegistry
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$FLARE_SYSTEMS_CALCULATOR" # FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x67c4B11c710D35a279A41cff5eb089Fe72748CF8" # Flare: Legacy FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x126FAeEc75601dA3354c0b5Cc0b60C85fCbC3A5e" # Songbird: Legacy FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x93F4C0b43A221Cf0a57faa882Df5E3F6CAa5Aca8" # Coston2: Legacy FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "0x3787dCBD770202F856ED9204c19d6f9022Ff3BF2" # Coston: Legacy FlareSystemsCalculator
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$RELAY" # Relay
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$FTSO_REWARD_OFFERS_MANAGER" # FtsoRewardOffersManager
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$FAST_UPDATER" # FastUpdater
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$FAST_UPDATE_INCENTIVE_MANAGER" # FastUpdateIncentiveManager
topic = "undefined"

[[indexer.collect_logs]]
contract_address = "$FDC_HUB" # FdcHub
topic = "undefined"

[db]
log_queries = false
drop_table_at_start = false
history_drop = 3628800 # 42 days

[logger]
level = "INFO"
file = "/tmp/flare-ftso-indexer.log"
console = true
